version: '3.8'

services:
  patrion-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patrion-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Backend API URL ve diğer ortam değişkenleri
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3001}
      - NEXT_PUBLIC_WEBSOCKET_URL=${NEXT_PUBLIC_WEBSOCKET_URL:-ws://localhost:3001}
    networks:
      - patrion-network

networks:
  patrion-network:
    driver: bridge 